# serverless.yml

service: oneupwebapp-demo

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2

functions:
  server:
    handler: index.server
    events:
      - http: # this is an API Gateway HTTP event trigger 
          path: /
          method: ANY
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY      

package:
  exclude:
    - .eslintignore
    - .eslintrc
    - .prettierrc
    - .next

plugins:
  - serverless-offline
